<!--  Menu    -->
<div class="be-left-sidebar">
    <div class="left-sidebar-wrapper">
        <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
                <div class="left-sidebar-content">
                    <ul class="sidebar-elements">

                        <li class="divider">Menu</li>

                        <div class="panel-group" role="tablist">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="collapseListGroupHeading2">
                                    <a href="#collapseListGroup2" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="collapseListGroup2"> <i class="icon mdi mdi-layers"></i><span> Usuario</span> </a>
                                </div>
                                <div class="panel-collapse collapse in" role="tabpanel" id="collapseListGroup2" aria-labelledby="collapseListGroupHeading2" aria-expanded="true">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud"
                                                role="button">Generar Solicitud</a></li>
                                    </ul>

                                </div>
                            </div>
                        </div>

                        <div class="panel-group" role="tablist">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="collapseListGroupHeading3">
                                    <a href="#collapseListGroup3" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="collapseListGroup3"> <i class="icon mdi mdi-layers"></i><span> Administración </span> </a>
                                </div>
                                <div class="panel-collapse collapse in" role="tabpanel" id="collapseListGroup3" aria-labelledby="collapseListGroupHeading3" aria-expanded="true">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-admin-activo" role="button">Admin de Inventario</a></li>
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-fisico" role="button"> Cat. Estado físico</a></li>
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-metodo-solicitud" role="button"> Cat. Motivo de solicitud</a></li>
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-tipo-asignacion" role="button"> Cat. Tipo de asignación</a></li>
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-categoria-activo" role="button"> Categoria activo</a></li>
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-tipo-activo" role="button"> Cat. Tipo de activo</a></li>
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-ubicacion" role="button"> Cat. Ubicación</a> </li>
                                        <li class="list-group-item"><a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-proveedor" role="button"> Cat. Proveedor</a>  </li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud-admin/idEstatus/0"
                                                role="button">Gestionar Solicitud</a></li>
                                        <li class="list-group-item">Reporte</li>
                                        <li class="list-group-item">Generacion de responsivas</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!--CONTENIDO-->
<div class="be-content">
    <!-- Titulo Modulo -->
    <div class="card-header card-header-divider">Cátalogo Estado Fisica<span class="card-subtitle">Este módulo permite registrar, editar y deshabilitar los estados fisicos de los activos.</span></div>

    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <!-- Inicio Botones -->
                <div class="mt-2 mb-2">
                    <button data-toggle="modal" data-target="#form-bp1" class="btn btn-space btn-success btn-big"><i
                            class="icon mdi mdi-collection-plus"></i> Registrar
                    </button>
                    <button class="btn btn-space btn-primary btn-big"><i class="icon mdi mdi-collection-text"></i>
                        Masiva
                    </button>
                </div>

                <!-- Titulo Modulo -->
                <div class="card card-table">
                    <div class="card-body">
                        <!-- Inicio de tabla -->
                        <table id="dt_proveedor" class="display">
                            <thead>
                            <tr>
                                <th>CÓDIGO</th>
                                <th>NOMBRE</th>
                                <th>DESCRIPCIÓN</th>
                                <th>ESTATUS</th>
                                <th>ACCIÓN</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <!-- FIN  Inicio de tabla -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/activo/view-fisico.js"></script>

<!--MODAL-->
<div id="form-bp1" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-success"
     aria-hidden="true">
    <div class="modal-dialog">
        <form id="formCatalogo" name="formCatalogo">
            <!-- Campos hidden -->
            <input id="inptProceso" name="inptProceso" type="hidden" value="Guardar"/>
            <input id="inpId" name="inpId" type="hidden" />
            <input id="inpTipoCatalogo" name="inpTipoCatalogo" type="hidden" value="ESTADO_FISICO" />

            <div class="modal-content">
                <div class="modal-header modal-header-colored">
                    <h3 id="bntTitulomodal" class="modal-title"> <i class="icon mdi mdi-collection-plus"></i> Registrar Esatdo Físico del Activo</h3>
                    <button name="btnCerrarX" type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span
                            class="mdi mdi-close"> </span></button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Nombre :</h5></label>
                        <input id="inpNombre" name="inpNombre" type="text" placeholder="Ingrese nombre proveedor" class="form-control soloLetrasNum">
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>
                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Descripción :</h5></label>
                        <textarea id="inpDes" name="inpDes" placeholder="Ingrese una descripción del proveedor" class="form-control soloLetrasNum" cols="3" rows="3" ></textarea>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"> <b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="custom-control">
                                ( * )  <span class="custom-control-label">Los campos con asterisco son obligatorios.</span>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label id="msjRespuesta" class="custom-control">  </label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnCerrar" name="btnCerrar" type="button" data-dismiss="modal" class="btn btn-default md-close">Cancel</button>
                    <button id="btnRegistrar" name="btnRegistrar" type="submit" class="btn btn-success">Registar</button>
                </div>
            </div>
        </form>
    </div>
</div>