<!--  Menu    -->
<input id="idEstatus" name="idEstatus" type="text" value="<?php echo $this->IDESTATUS; ?>"/>
<div class="be-left-sidebar">
    <div class="left-sidebar-wrapper">
        <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
                <div class="left-sidebar-content">
                    <ul class="sidebar-elements">

                        <li class="divider">Menu</li>
                        <div class="panel-group" role="tablist">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="collapseListGroupHeading2">
                                    <a href="#collapseListGroup2" role="button" data-toggle="collapse"
                                       aria-expanded="true" aria-controls="collapseListGroup2"> <i
                                            class="icon mdi mdi-layers"></i><span> Usuario</span> </a>
                                </div>
                                <div class="panel-collapse collapse in" role="tabpanel" id="collapseListGroup2"
                                     aria-labelledby="collapseListGroupHeading2" aria-expanded="true">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud"
                                                role="button">Generar Solicitud</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel-group" role="tablist">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="collapseListGroupHeading3">
                                    <a href="#collapseListGroup3" role="button" data-toggle="collapse"
                                       aria-expanded="true" aria-controls="collapseListGroup3"> <i
                                            class="icon mdi mdi-layers"></i><span> Administración </span> </a>
                                </div>
                                <div class="panel-collapse collapse in" role="tabpanel" id="collapseListGroup3"
                                     aria-labelledby="collapseListGroupHeading3" aria-expanded="true">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-admin-activo"
                                                role="button">Admin de Inventario</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-fisico"
                                                role="button"> Cat. Estado físico</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-metodo-solicitud"
                                                role="button"> Cat. Motivo de solicitud</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-tipo-asignacion"
                                                role="button"> Cat. Tipo de asignación</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-categoria-activo"
                                                role="button"> Categoria activo</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-tipo-activo"
                                                role="button"> Cat. Tipo de activo</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-ubicacion"
                                                role="button"> Cat. Ubicación</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-proveedor"
                                                role="button"> Cat. Proveedor</a></li>
                                        <li class="list-group-item"><a
                                                href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud-admin/idEstatus/0"
                                                role="button">Gestionar Solicitud</a></li>
                                        <li class="list-group-item">Reporte</li>
                                        <li class="list-group-item">Generacion de responsivas</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!--CONTENIDO-->
<div class="be-content">
    <!-- Titulo Modulo -->
    <div class="card-header card-header-divider">Listado de Solicitudes<span class="card-subtitle">Este módulo permite registrar, editar y rechazar las solicitudes.</span>
    </div>

    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-12 col-lg-6 col-xl-3">
                <div class="widget widget-tile">
                    <div class="data-info">
                        <div class="desc">Solicitudes</div>
                        <div class="value"><span class="indicator indicator-equal mdi mdi-chevron-right"></span><span data-toggle="counter" class="number">
                                <a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud-admin/idEstatus/1" role="button"> 113 </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 col-xl-3">
                <div class="widget widget-tile">
                    <div class="data-info">
                        <div class="desc">Pendiente Entrega</div>
                        <div class="value"><span class="indicator indicator-positive mdi mdi-chevron-up"></span><span data-toggle="counter" class="number">
                                <a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud-admin/idEstatus/3" role="button"> 113 </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 col-xl-3">
                <div class="widget widget-tile">
                    <div class="data-info">
                        <div class="desc">Rechazadas</div>
                        <div class="value"><span class="indicator indicator-positive mdi mdi-chevron-up"></span><span data-toggle="counter" class="number">
                                <a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud-admin/idEstatus/2" role="button"> 113 </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-6 col-xl-3">
                <div class="widget widget-tile">
                    <div class="data-info">
                        <div class="desc">Entregados</div>
                        <div class="value"><span class="indicator indicator-positive mdi mdi-chevron-up"></span><span data-toggle="counter" class="number">
                                <a href="http://localhost/GitDesarrollo/activoZend/public/controlactivos/index/view-solicitud-admin/idEstatus/4" role="button"> 113 </a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">
                        <!-- Inicio de tabla -->
                        <table id="dt_solicitud" class="display">
                            <thead>
                            <tr>
                                <th>CO. TRACKING</th>
                                <th>USUARIO</th>
                                <th>ACTIVO</th>
                                <th>SOLICITANTE</th>
                                <th>MOTIVO</th>
                                <th>ESTATUS</th>
                                <th>FECHA</th>
                                <th>ACCIÓN</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <!-- FIN  Inicio de tabla -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/activo/view-solicitud-admin.js"></script>

<!--MODAL-->
<div id="form-bp1" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-success"
     aria-hidden="true">
    <div class="modal-dialog">
        <form id="formSolicitud" name="formSolicitud">
            <!-- Campos hidden -->
            <input id="inptProceso" name="inptProceso" type="hidden" value="Guardar"/>
            <input id="inpId" name="inpId" type="hidden"/>
            <input id="inpSolicitante" name="inpSolicitante" type="hidden" value="20112"/>


            <div class="modal-content">
                <div class="modal-header modal-header-colored">
                    <h3 id="bntTitulomodal" class="modal-title"><i class="icon mdi mdi-collection-plus"></i> Registrar
                        Solicitud</h3>
                    <button name="btnCerrarX" type="button" data-dismiss="modal" aria-hidden="true"
                            class="close md-close"><span
                            class="mdi mdi-close"> </span></button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Categoría del Activo:</h5></label>
                        <input id="inpCategoria" name="inpCategoria" type="hidden"/>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"><b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                        <select id="selCategoria" name="selCategoria" class="form-control">
                            <option value="default">[Seleccione]</option>
                            <?php foreach ($this->CATEGORIA as $key => $val): ?>
                                <option
                                    value="<?php echo $this->escape($val['ID_CACT_CATEGORIA']) ?>"><?php echo $this->escape($val['NOM_CATEGORIA']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Tipo de activo: </h5></label>
                        <input id="inpTipoActivo" name="inpTipoActivo" type="hidden"/>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"><b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                        <select id="selTipoActivo" name="selTipoActivo" class="form-control">
                            <option value="default">[Seleccione]</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Motivo de la solicitud: </h5></label>
                        <input id="inpMotivo" name="inpMotivo" type="hidden"/>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"><b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                        <select id="selMotivo" name="selMotivo" class="form-control">
                            <option value="default">[Seleccione]</option>
                            <?php foreach ($this->MOTIVO as $key => $val): ?>
                                <option
                                    value="<?php echo $this->escape($val['ID_CACT_CATEGORIA']) ?>"><?php echo $this->escape($val['NOM_CATEGORIA']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>


                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Cantidad :</h5></label>
                        <input id="inpCantidad" name="inpCantidad" type="hidden"/>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"><b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                        <select id="selCantidad" name="selCantidad" class="form-control">
                            <option value="default">[Seleccione]</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Descripción motivo de la solicitud :</h5>
                        </label>
                        <textarea id="inpDes" name="inpDes" placeholder="Ingrese una descripción del proveedor"
                                  class="form-control soloLetrasNum" cols="3" rows="3"></textarea>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"><b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="custom-control">
                                ( * ) <span
                                    class="custom-control-label">Los campos con asterisco son obligatorios.</span>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label id="msjRespuesta" class="custom-control"> </label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnCerrar" name="btnCerrar" type="button" data-dismiss="modal"
                            class="btn btn-default md-close">Cerrar
                    </button>
                    <button id="btnRegistrar" name="btnRegistrar" type="submit" class="btn btn-success">Registar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<!--MODAL-->
<div id="modalBitacora" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-success"
     aria-hidden="true">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-header-colored">
                    <h3 id="bntTitulomodal" class="modal-title"><i class="mdi mdi-format-align-justify"></i> Bitácora  Solicitud</h3>
                    <button name="btnCerrarX" type="button" data-dismiss="modal" aria-hidden="true"
                            class="close md-close"><span
                            class="mdi mdi-close"> </span></button>
                </div>
                <div class="modal-body">

                    <div class="card card-table">
                        <div class="card-header">
                            <div class="title">Últimos Procesos</div>
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th style="width:20%;">Usuario</th>
                                    <th style="width:40%;">Comentario</th>
                                    <th>Fecha</th>
                                    <th>Estatus</th>
                                </tr>
                                </thead>
                                <tbody id="bitacora">

                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button id="btnCerrar" name="btnCerrar" type="button" data-dismiss="modal"
                            class="btn btn-default md-close">Cerrar
                    </button>
                </div>
            </div>
    </div>
</div>

<!--MODAL-->
<div id="form-bp2" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-warning"
     aria-hidden="true">
    <div class="modal-dialog">
        <form id="formSolicitudRecha" name="formSolicitudRecha">
            <!-- Campos hidden -->
            <input id="inptProceso" name="inptProceso" type="hidden" value="Editar"/>
            <input id="inpIdTracking" name="inpIdTracking" type="hidden" />
            <input id="inpSolicitante" name="inpSolicitante" type="hidden" value="20112"/>

            <div class="modal-content">
                <div class="modal-header modal-header-colored">
                    <h3 id="bntTitulomodal" class="modal-title"><i class="icon mdi mdi-edit"></i> Rechazar Solicitud</h3>
                    <button name="btnCerrarX" type="button" data-dismiss="modal" aria-hidden="true"
                            class="close md-close"><span
                            class="mdi mdi-close"> </span></button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label><h5> Tipo de activo: </h5></label>
                        <input id="inpTipoActivoRecha" name="inpTipoActivoRecha" class="form-control" type="text" value="" disabled/>

                    </div>

                    <div class="form-group">
                        <label><h5> Motivo de la solicitud: </h5></label>
                        <input id="inpMotivoRecha" name="inpMotivoRecha" type="text" class="form-control" value="" disabled />
                    </div>


                    <div class="form-group">
                        <label><h5> Cantidad :</h5></label>
                        <input id="inpCantidadRecha" name="inpCantidadRecha" type="text" class="form-control" value="" disabled />
                    </div>

                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Descripción motivo de la solicitud :</h5>
                        </label>
                        <textarea id="inpDes" name="inpDes" placeholder="Ingrese una descripción del proveedor"
                                  class="form-control soloLetrasNum" cols="3" rows="3"></textarea>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"><b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->
                    </div>

                    <div class="form-group">
                        <label><h5><span class="glyphicon-red"> ( * )</span> Estatus: </h5></label>
                        <input id="inpEstatus" name="inpEstatus" type="hidden"/>
                        <!-- Componente Mesj-->
                        <div class="error" style="display:none"><b class="border-notch notch"></b>
                        </div>
                        <!-- Componente Mesj-->

                        <select id="selEstatus" name="selEstatus" class="form-control">
                            <option value="default">[Seleccione]</option>
                            <?php foreach ($this->ESTATUS as $key => $val): ?>
                                <option value="<?php echo $this->escape($val['ID_ESTATUS']) ?>"><?php echo $this->escape($val['NOM_ESTATUS']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="custom-control">
                                ( * ) <span
                                    class="custom-control-label">Los campos con asterisco son obligatorios.</span>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label id="msjRespuestaRecha" class="custom-control"> </label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnCerrar" name="btnCerrar" type="button" data-dismiss="modal" class="btn btn-default md-close">Cerrar </button>
                    <button id="btnRechazar" name="btnRechazar" type="submit" class="btn btn-warning">Rechazar Solicitud </button>
                </div>
            </div>
        </form>
    </div>
</div>

